pipeline:
  test-ruby:
    image: ruby:2.4
    commands:
      - bundle install --path bundler
      - bundle exec rubocop --fail-level A -S --format c --parallel
      - bundle exec rspec spec/
  test-shellcheck:
    image: koalaman/shellcheck-alpine:latest
    commands:
      - apk update && apk add bash
      - bash -c 'shopt -s globstar; shellcheck **/*.sh'
  create_gh_release:
    image: ubuntu:xenial
    secrets: [ github_token ]
    commands:
      - ./build/drone/create_release.sh
    when:
      event: tag
  build_xenial:
    image: ubuntu:xenial
    secrets: [ github_token ]
    environment:
      - CPPFLAGS=-P
    commands:
      - ./build/drone/ubuntu_xenial.sh
    when:
      event: tag
  release_binary:
    image: plugins/s3
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    bucket: pharos-cluster-binaries
    region: eu-west-1
    source: "pharos-cluster-linux-amd64-${DRONE_TAG##v}"
    target: /
    when:
      event: tag