kind: pipeline
name: test
platform:
  os: linux
  arch: amd64
steps:
  - name: test-ruby
    image: ruby:2.5
    commands:
      - gem install bundler -Nf
      - bundle install --path bundler
      - bundle exec rubocop --fail-level A -S --format c --parallel
      - bundle exec rspec spec/
      - PHAROS_NON_OSS=true bundle exec rspec spec/ non-oss/spec/
  - name: test-shellcheck
    image: koalaman/shellcheck-alpine:latest
    commands:
      - apk update && apk add bash
      - bash -c 'shopt -s globstar; shellcheck **/*.sh'
---
kind: pipeline
name: e2e-bionic
depends_on:
- test
platform:
  os: linux
  arch: amd64
steps:
  # E2E steps
  - name: setup-bionic-e2e
    image: docker.io/hashicorp/terraform:0.11.10
    environment:
      DIGITALOCEAN_TOKEN:
        from_secret: digitalocean_token
    commands:
      - ./e2e/drone_setup.sh ubuntu-18-04-x64
    when:
      event: [ push ]
  - name: bionic-e2e
    image: ruby:2.5
    commands:
      - gem install bundler -Nf
      - bundle install --path bundler
      - ./e2e/drone.sh
    when:
      event: [ push ]
  - name: teardown-bionic-e2e
    image: docker.io/hashicorp/terraform:0.11.10
    environment:
      DIGITALOCEAN_TOKEN:
        from_secret: digitalocean_token
    commands:
      - ./e2e/drone_teardown.sh
    when:
      event: [ push ]
      status: [ failure, success ]
---
kind: pipeline
name: e2e-centos
depends_on:
- test
platform:
  os: linux
  arch: amd64
steps:
  - name: setup-centos-e2e
    image: docker.io/hashicorp/terraform:0.11.10
    environment:
      DIGITALOCEAN_TOKEN:
        from_secret: digitalocean_token
    commands:
      - ./e2e/drone_setup.sh centos-7-x64
    when:
      event: [ push ]
  - name: centos-e2e
    image: ruby:2.5
    commands:
      - gem install bundler -Nf
      - bundle install --path bundler
      - ./e2e/drone.sh
    when:
      event: [ push ]
  - name: teardown-centos-e2e
    image: docker.io/hashicorp/terraform:0.11.10
    environment:
      DIGITALOCEAN_TOKEN:
        from_secret: digitalocean_token
    commands:
      - ./e2e/drone_teardown.sh
    when:
      event: [ push ]
      status: [ failure, success ]
