kind: pipeline
name: default
platform:
  os: linux
  arch: amd64
steps:
  - name: test-ruby
    image: ruby:2.5
    commands:
      - gem install bundler -Nf
      - bundle install --path bundler
      - bundle exec rubocop --fail-level A -S --format c --parallel
      - bundle exec rspec spec/
      - PHAROS_NON_OSS=true bundle exec rspec spec/ non-oss/spec/
  - name: test-shellcheck
    image: koalaman/shellcheck-alpine:latest
    commands:
      - apk update && apk add bash
      - bash -c 'shopt -s globstar; shellcheck **/*.sh'
