kind: pipeline
name: e2e-bionic
platform:
  os: linux
  arch: amd64
steps:
  # E2E steps
  - name: setup-bionic-e2e
    image: docker.io/hashicorp/terraform:0.11.10
    environment:
      DIGITALOCEAN_TOKEN:
        from_secret: digitalocean_token
    commands:
      - ./e2e/drone_setup.sh ubuntu-18-04-x64
    when:
      event: [ push ]
  - name: bionic-e2e
    image: ruby:2.5
    commands:
      - ./e2e/drone.sh
    when:
      event: [ push ]
  - name: teardown-bionic-e2e
    image: docker.io/hashicorp/terraform:0.11.10
    environment:
      DIGITALOCEAN_TOKEN:
        from_secret: digitalocean_token
    commands:
      - ./e2e/drone_teardown.sh
    when:
      event: [ push ]
      status: [ failure, success ]
