inherit_from: .rubocop.relaxed.yml

AllCops:
  Exclude:
    - spec/**/*
    - non-oss/spec/**/*
    - Gemfile
    - "*.gemspec"
    - bundler/**/*
  TargetRubyVersion: 2.5

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Style/FormatString:
  EnforcedStyle: percent

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/WordArray:
  Enabled: true
  MinSize: 3

Style/SymbolArray:
  Enabled: true
  MinSize: 3

Gemspec/OrderedDependencies:
  Enabled: false

Style/PerlBackrefs:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/Alias:
  Enabled: true

Style/BeginBlock:
  Enabled: true

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - cn

Metrics/BlockLength:
  Enabled: false
