pharos-cluster:
  build: .
  volumes:
  - .:/app
  - $SSH_AUTH_SOCK:/run/ssh-agent.sock
  - ./.pharos:/root/.pharos
  environment:
  - SSH_AUTH_SOCK=/run/ssh-agent.sock
  entrypoint: bin/pharos-cluster
  command: up
