apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: user-management
  namespace: kontena-lens
  labels:
    app: user-management
spec:
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      tolerations:
        - effect: NoSchedule
          operator: Exists
      serviceAccountName: lens-operator
      containers:
        - image: quay.io/kontena/lens-idp:2018.6.1
          name: user-management
          imagePullPolicy: Always
          env:
            - name: KUBERNETES_NAMESPACE
              value: kontena-lens
          resources:
            requests:
              memory: "128Mi"
              cpu: "20m"
            limits:
              memory: "256Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /ping
              port: 9999
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 5