apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: lens-config-manager
  namespace: kontena-lens
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - '*'
