apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: read-pharos-config
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pharos-config-reader
subjects:
  - kind: ServiceAccount
    name: lens-operator
    namespace: kontena-lens