apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pharos-config-reader
  namespace: kube-system
rules:
  - apiGroups:
      - ''
    resourceNames:
      - pharos-config
    resources:
      - configmaps
    verbs:
      - get