apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-cainjector
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: kube-system
