apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    app: webhook

