apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: manage-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user-manager
subjects:
  - kind: ServiceAccount
    name: lens-operator
    namespace: kontena-lens