apiVersion: v1
kind: ServiceAccount
metadata:
  name: license-enforcer
  namespace: kontena-lens
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: license-enforcer
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames:
    - "license-enforcer"
  verbs:
    - get
    - list
- apiGroups: ["apps"]
  resources: ["deployments/status"]
  resourceNames:
    - "license-enforcer"
  verbs:
    - update # To be able to push license status
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames:
    - pharos-license
  verbs:
    - get
    - update
    - patch
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames:
    - "cluster-info"
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: license-enforcer
  namespace: kontena-lens
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: license-enforcer
subjects:
- name: license-enforcer
  kind: ServiceAccount
  namespace: kontena-lens
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: license-enforcer
  namespace: kube-public
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: license-enforcer
subjects:
- name: license-enforcer
  kind: ServiceAccount
  namespace: kontena-lens
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: license-enforcer
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: license-enforcer
subjects:
- name: license-enforcer
  kind: ServiceAccount
  namespace: kontena-lens
