apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: manage-lens-config
  namespace: kontena-lens
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lens-config-manager
subjects:
  - kind: ServiceAccount
    name: lens-operator
    namespace: kontena-lens