# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/7"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  3.times.each do |i|
    vm_name = "host-%<index>02d" % { index: i }
    config.vm.define(vm_name) do |host|
      host.vm.hostname = vm_name
      host.ssh.insert_key = false
      host.vm.provider :virtualbox do |vb|
        vb.gui = false
        vb.memory = "2048"
        vb.cpus = 1
      end

      host.vm.network "private_network", ip: "192.168.100.#{i + 100}"
      host.vm.provision("shell", path: 'proxy-only.sh') if ENV['VAGRANT_HTTP_PROXY']
    end
  end
end
