# Grant the operator, agent, and discovery agents access to resources in the kontena-storage-system namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kontena-storage-system
  namespace: kontena-storage-system
  labels:
    operator: rook
    storage-backend: ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kontena-storage-system
subjects:
- kind: ServiceAccount
  name: kontena-storage-system
  namespace: kontena-storage-system