kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kontena-storage-cluster
  namespace: kontena-storage
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: [ "get", "list", "watch", "create", "update", "delete" ]