apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: kontena-storage-block
   annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ceph.rook.io/block
parameters:
  pool: replicapool
  clusterNamespace: kontena-storage