apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-proxy
  namespace: kontena-stats
data:
  config.yaml: |+
    authorization:
      rewrites:
        byQueryParameter:
          name: "kubernetes_namespace"
      resourceAttributes:
        apiVersion: v1beta1
        apiGroup: metrics.k8s.io
        resource: pods
        namespace: "{{ .Value }}"
