# The rook system service account used by the operator, agent, and discovery pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kontena-storage-system
  namespace: kontena-storage-system
  labels:
    operator: rook
    storage-backend: ceph