kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kontena-storage-cluster
  namespace: kontena-storage
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: [ "get", "list", "watch", "create", "update", "delete" ]
- apiGroups:
  - policy
  resourceNames:
  - 00-pharos-privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use