# Allow the operator to create resources in this cluster's namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kontena-storage-cluster-mgmt
  namespace: kontena-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kontena-storage-cluster-mgmt
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: kontena-storage-system
---
# Allow the osd pods in this namespace to work with configmaps
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kontena-storage-osd
  namespace: kontena-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kontena-storage-osd
subjects:
- kind: ServiceAccount
  name: rook-ceph-osd
  namespace: kontena-storage
---
# Allow the ceph mgr to access the cluster-specific resources necessary for the mgr modules
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kontena-storage-mgr
  namespace: kontena-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kontena-storage-mgr
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: kontena-storage
---
# Allow the ceph mgr to access the rook system resources necessary for the mgr modules
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kontena-storage-mgr-system
  namespace: kontena-storage-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kontena-storage-mgr-system
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: kontena-storage
---
# Allow the ceph mgr to access cluster-wide resources necessary for the mgr modules
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kontena-storage-mgr-cluster
  namespace: kontena-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kontena-storage-mgr-cluster
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: kontena-storage
