apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cephfs-provisioner
  namespace: kontena-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cephfs-provisioner
  namespace: kontena-storage
subjects:
- kind: ServiceAccount
  name: cephfs-provisioner
  namespace: kontena-storage