apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-prom-exporter
  namespace: kontena-storage
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ceph-prom-exporter
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs:
      - get
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ceph-prom-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ceph-prom-exporter
subjects:
  - name: ceph-prom-exporter
    namespace: kontena-storage
    kind: ServiceAccount
