apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kontena-network-lb-system:speaker
  labels:
    app: kontena-network-lb
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "nodes"]
  verbs: ["get", "list", "watch"]