apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kontena-network-lb-system
  name: config-watcher
  labels:
    app: kontena-network-lb
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]