apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kontena-network-lb-system:speaker
  labels:
    app: kontena-network-lb
subjects:
- kind: ServiceAccount
  name: speaker
  namespace: kontena-network-lb-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kontena-network-lb-system:speaker