apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openebs-psp
  namespace: storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pharos:podsecuritypolicy:privileged
subjects:
- kind: ServiceAccount
  name: openebs-maya-operator
  namespace: storage